### PR TITLE
Remove dependency for Requests package

### PR DESCRIPTION
**Pull request by StephDC**
I would like to use as less 3rd party lib as possible in order to simplify the installation process.
This is now only coded as a fallback method, but I think you might be able to make it as the default method.

### CODE REVIEW

**Comment by RihanWu** [comment]
I have created a branch for this to be tested out. You can check that out.
@StephDC

**Comment by StephDC** [comment]
It is ready to be tested.
I also added the invoke.py for better? command line experience.

**Comment by RihanWu** [comment]
Maybe try this?
https://docs.python.org/3.5/library/argparse.html

**Comment by StephDC** [comment]
I'll consider to rewrite it later in argparse.
Should this program have an interface like this? Or should it only include an interactive CLI and a GUI?

```
VocabTool

usage:  invoke.py [-h | -i | -l]
    invoke.py [-d Dictionary] [-f Format] [-o Output] word

    d: Specify which dictionary to use. Use multiple times
       to specify multiple dictionaries. Default: all.
    f: Specify which format the output should be. Available
       choices: text, rtf, pdf. Default: text.
    h: Print this help message.
    i: Invoke interactive text interface.
    l: List all of the available dictionaries.
    o: Specify the output file. Default: standard output.
```

**Comment by RihanWu** [comment]
In my opinion, we can keep the CLI simple for now since only a few functions are implemented. 
We don't have underlining functions to support the -d, -f, and -o options yet.
However, you can design it to be extendable.
BTW, try to follow PEP8 in your code.

**Comment by RihanWu** [comment]
I have created two separate branches for the two features. You can check them out.

**Pull request closed without merging**
